[package]
name = "abc_405"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
